---
  - name: Elk Stack Ansible Playbook
    hosts: elk
    become: true
    tasks:

    - name: Install docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install pip module docker
      pip:
        name: docker
        state: present

    - name: Increase virtual memory for Elasticsearch
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        sysctl_set: yes
        reload: yes

    - name: Install sebp/elk:761 Docker container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Ensure docker is enabled
      systemd:
        name: docker
        enabled: yes
        state: started