---
  - name: Web Servers Ansible Playbook
    hosts: webservers
    become: true
    tasks:

    - name: Install docker
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install pip module docker
      pip:
        name: docker
        state: present

    - name: Install cyberxsecurity/dvwa Docker container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Ensure docker is enabled
      systemd:
        name: docker
        enabled: yes
        state: started